name: Go

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: |
        go test ./data -c
        ./data.test -test.v
        go test ./statistics -c
        ./statistics.test -test.v
